<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-30 23:00

from django.db import migrations, models
import django.utils.timezone
=======
# Generated by Django 4.1.2 on 2022-11-07 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> WIN-26-Custom_user_profile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> WIN-26-Custom_user_profile
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=100)),
=======
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('major', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> WIN-26-Custom_user_profile
            ],
        ),
    ]
