version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dependencies
          command: pip install pytest
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  sample:
    jobs:
      - build-and-test

        filters:
          branches:
            only:
              -master
