# Generated by Django 4.1.2 on 2022-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='content',
        ),
        migrations.RemoveField(
            model_name='books',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
