# Generated by Django 4.1.2 on 2022-12-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
    ]
