# Generated by Django 4.1.2 on 2022-12-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_auto_20221201_1030'),
    ]

    operations = [
    ]
