# Generated by Django 4.1.2 on 2022-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_remove_books_content_remove_books_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
